.\" Process this file with
.\" groff -man -Tascii impfe.1
.\"
.TH IMPFE 1 "MAY 2015" Linux "User Manuals"
.SH NAME
impfe \- Graphical client for Imperium
.SH SYNOPSIS
.B impfe
.SH DESCRIPTION
.B impfe
is a graphical client for
.BR Imperium (1)
that also supports scripting and offline data viewing.
.SH FILES
.I /bin/impfe.music.mp3
.RS
Startup music
.RE
.I *.fe
.RS
Per game configuration files
.RE
.I *-items
.RS
Per game items database
.RE
.I *-planets
.RS
Per game planet database
.RE
.I *-players
.RS
Per game players database
.RE
.I *-races
.RS
Per game races database
.RE
.I *-sectors
.RS
Per game sectors database
.RE
.I *-sectors-bitmap
.RS
Per game sectors bitmap database
.RE
.I *-ships
.RS
Per game ship database
.RE
.SH BUGS
None reported
.SH AUTHOR
Marisa Giancarla <fstltna@yahoo.com>
.SH "SEE ALSO"
.BR Imperium (1),

