/* Form definition file generated by fdesign on Sun May  1 03:02:11 2022 */

#include <stdlib.h>
#include "ImpFeGui.h"


/***************************************
 ***************************************/

FD_ImpFeMain *
create_form_ImpFeMain( void )
{
    FL_OBJECT *obj;
    FD_ImpFeMain *fdui = ( FD_ImpFeMain * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->ImpFeMain = fl_bgn_form( FL_NO_BOX, 650, 470 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 650, 470, "" );
    fl_set_object_resize( obj, FL_RESIZE_Y );

    obj = fl_add_text( FL_NORMAL_TEXT, 480, 50, 40, 20, "BTU" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->HdnRtn = obj = fl_add_button( FL_HIDDEN_RET_BUTTON, 430, 400, 20, 20, "" );
    fl_set_button_shortcut( obj, "^M", 1 );
    fl_set_object_boxtype( obj, FL_NO_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, HdnRtn_cb, 0 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 650, 40, "" );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->MainInputBox = obj = fl_add_input( FL_NORMAL_INPUT, 90, 430, 550, 30, "" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT_TOP );
    fl_set_object_lstyle( obj, FL_FIXED_STYLE );
    fl_set_object_resize( obj, -2 );
    fl_set_object_gravity( obj, FL_SouthWest, FL_SouthEast );
    fl_set_object_callback( obj, MainInputBox_cb, 0 );

    fdui->MainHelpMenu = obj = fl_add_menu( FL_PULLDOWN_MENU, 600, 10, 40, 20, "Help" );
    fl_set_object_shortcut( obj, "#H", 1 );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MainHelpMenu_cb, 0 );

    fdui->MainBrowser = obj = fl_add_browser( FL_NORMAL_BROWSER, 10, 80, 630, 300, "" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lstyle( obj, FL_FIXED_STYLE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->PrivMsgBtn = obj = fl_add_roundbutton( FL_PUSH_BUTTON, 30, 390, 30, 30, "Priv" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_MCOL, FL_RED );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, PrivMsgBtn_cb, 0 );

    fdui->MainFileMenu = obj = fl_add_menu( FL_PULLDOWN_MENU, 10, 10, 40, 20, "File" );
    fl_set_object_shortcut( obj, "#F", 1 );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MainFileMenu_cb, 0 );

    fdui->MainServerMenu = obj = fl_add_menu( FL_PULLDOWN_MENU, 50, 10, 50, 20, "Server" );
    fl_set_object_shortcut( obj, "#S", 1 );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MainServerMenu_cb, 0 );

    obj = fl_add_box( FL_NO_BOX, 0, 380, 650, 10, "@UpLine" );

    fdui->PrivMsgWho = obj = fl_add_input( FL_NORMAL_INPUT, 10, 430, 70, 20, "" );
    fl_set_object_lstyle( obj, FL_FIXED_STYLE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, PrivMsgWho_cb, 0 );

    obj = fl_add_box( FL_UP_BOX, 80, 390, 10, 80, "" );
    fl_set_object_resize( obj, FL_RESIZE_Y );

    fdui->MainViewMenu = obj = fl_add_menu( FL_PULLDOWN_MENU, 100, 10, 40, 20, "View" );
    fl_set_object_shortcut( obj, "#V", 1 );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MainViewMenu_cb, 0 );

    fdui->MainConfigMenu = obj = fl_add_menu( FL_PULLDOWN_MENU, 530, 10, 70, 20, "Configure" );
    fl_set_object_shortcut( obj, "#C", 1 );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MainConfigMenu_cb, 0 );

    fdui->MainPrompt = obj = fl_add_text( FL_NORMAL_TEXT, 150, 390, 490, 40, "" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_INDIANRED, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    obj = fl_add_text( FL_NORMAL_TEXT, 90, 390, 60, 40, "Prompt:" );
    fl_set_object_boxtype( obj, FL_NO_BOX );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->BtuDisp = obj = fl_add_text( FL_NORMAL_TEXT, 520, 50, 30, 20, "" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->TimeDisp = obj = fl_add_text( FL_NORMAL_TEXT, 600, 50, 40, 20, "" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    obj = fl_add_text( FL_NORMAL_TEXT, 560, 50, 40, 20, "TIME" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    obj = fl_add_text( FL_NORMAL_TEXT, 330, 50, 60, 20, "STATUS" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->StatusBox = obj = fl_add_text( FL_NORMAL_TEXT, 390, 50, 80, 20, "Offline" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    obj = fl_add_text( FL_NORMAL_TEXT, 200, 50, 90, 20, "CMD QUEUE" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->QueueDisp = obj = fl_add_text( FL_NORMAL_TEXT, 290, 50, 30, 20, "" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    obj = fl_add_text( FL_NORMAL_TEXT, 30, 50, 130, 20, "ACTIVE SCRIPTS" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->ScriptDisp = obj = fl_add_text( FL_NORMAL_TEXT, 160, 50, 30, 20, "" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fl_end_form( );

    fdui->ImpFeMain->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_ImpFeAbout *
create_form_ImpFeAbout( void )
{
    FL_OBJECT *obj;
    FD_ImpFeAbout *fdui = ( FD_ImpFeAbout * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->ImpFeAbout = fl_bgn_form( FL_NO_BOX, 320, 300 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 320, 300, "" );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->AboutOkButn = obj = fl_add_button( FL_NORMAL_BUTTON, 110, 260, 80, 30, "OK" );
    fl_set_button_shortcut( obj, "Oo", 1 );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, AboutOk_cb, 0 );

    fdui->MainAboutText = obj = fl_add_text( FL_NORMAL_TEXT, 10, 110, 300, 140, "(C) 1997 Marisa Giancarla" );
    fl_set_object_boxtype( obj, FL_DOWN_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT_TOP | FL_ALIGN_INSIDE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->ImpVer = obj = fl_add_text( FL_NORMAL_TEXT, 170, 20, 100, 30, "ImpFE v0.0.1" );
    fl_set_object_lcolor( obj, FL_WHITE );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE + FL_ENGRAVED_STYLE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->ImpLogo = obj = fl_add_pixmap( FL_NORMAL_PIXMAP, 20, 20, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fl_end_form( );

    fdui->ImpFeAbout->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_MapForm *
create_form_MapForm( void )
{
    FL_OBJECT *obj;
    FD_MapForm *fdui = ( FD_MapForm * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->MapForm = fl_bgn_form( FL_NO_BOX, 760, 470 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 760, 470, "" );

    fdui->AA = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 510, 70, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 10 );

    obj = fl_add_box( FL_UP_BOX, 580, 50, 170, 170, "" );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 760, 40, "" );

    fdui->MapHelpMenu = obj = fl_add_menu( FL_PULLDOWN_MENU, 700, 10, 50, 20, "Help" );
    fl_set_object_shortcut( obj, "H", 1 );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_callback( obj, MapHelpMenu_cb, 0 );

    fdui->MapFileMenu = obj = fl_add_menu( FL_PULLDOWN_MENU, 10, 10, 40, 20, "File" );
    fl_set_object_shortcut( obj, "F", 1 );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_callback( obj, MapFileMenu_cb, 0 );

    fdui->UpBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 650, 90, 30, 30, "@8->" );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 8 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->DnBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 650, 150, 30, 30, "@2->" );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 2 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->RtBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 680, 120, 30, 30, "@->" );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 6 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->LtBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 620, 120, 30, 30, "@4->" );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 4 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->DRBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 680, 150, 30, 30, "@3->" );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 3 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->URBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 680, 90, 30, 30, "@9->" );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 9 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->ULBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 620, 90, 30, 30, "@7->" );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 7 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->DLBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 620, 150, 30, 30, "@1->" );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 1 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->BigUpBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 650, 60, 30, 30, "@8>>" );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 80 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->BigRtBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 710, 120, 30, 30, "@>>" );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 60 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->BigDnBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 650, 180, 30, 30, "@2>>" );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 20 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->BigLtBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 590, 120, 30, 30, "@4>>" );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 40 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->BigURBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 710, 60, 30, 30, "@9>>" );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 90 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->BigDRBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 710, 180, 30, 30, "@3>>" );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 30 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->BigULBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 590, 60, 30, 30, "@7>>" );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 70 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->BigDLBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 590, 180, 30, 30, "@1>>" );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 10 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->MapCellGroup = fl_bgn_group( );

    fdui->A1 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 60, 70, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 1 );

    fdui->B1 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 60, 120, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 11 );

    fdui->C1 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 60, 170, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 21 );

    fdui->D1 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 60, 220, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 31 );

    fdui->E1 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 60, 270, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 41 );

    fdui->F1 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 60, 320, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 51 );

    fdui->G1 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 60, 370, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 61 );

    fdui->A2 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 110, 70, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 2 );

    fdui->A3 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 160, 70, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 3 );

    fdui->A4 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 210, 70, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 4 );

    fdui->A5 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 260, 70, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 5 );

    fdui->A6 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 310, 70, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 6 );

    fdui->A7 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 360, 70, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 7 );

    fdui->A8 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 410, 70, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 8 );

    fdui->A9 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 460, 70, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 9 );

    fdui->B2 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 110, 120, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 12 );

    fdui->B3 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 160, 120, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 13 );

    fdui->B4 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 210, 120, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 14 );

    fdui->B5 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 260, 120, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 15 );

    fdui->B6 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 310, 120, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 16 );

    fdui->B8 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 410, 120, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 18 );

    fdui->B9 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 460, 120, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 19 );

    fdui->B7 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 360, 120, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 17 );

    fdui->C2 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 110, 170, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 22 );

    fdui->C3 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 160, 170, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 23 );

    fdui->C4 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 210, 170, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 24 );

    fdui->C5 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 260, 170, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 25 );

    fdui->C6 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 310, 170, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 26 );

    fdui->C7 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 360, 170, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 27 );

    fdui->C8 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 410, 170, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 28 );

    fdui->C9 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 460, 170, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 29 );

    fdui->D2 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 110, 220, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 32 );

    fdui->D3 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 160, 220, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 33 );

    fdui->D4 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 210, 220, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 34 );

    fdui->D5 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 260, 220, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 35 );

    fdui->D6 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 310, 220, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 36 );

    fdui->D7 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 360, 220, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 37 );

    fdui->D8 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 410, 220, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 38 );

    fdui->D9 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 460, 220, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 39 );

    fdui->E2 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 110, 270, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 42 );

    fdui->E3 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 160, 270, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 43 );

    fdui->E4 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 210, 270, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 44 );

    fdui->E5 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 260, 270, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 45 );

    fdui->E6 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 310, 270, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 46 );

    fdui->E7 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 360, 270, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 47 );

    fdui->E8 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 410, 270, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 48 );

    fdui->E9 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 460, 270, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 49 );

    fdui->F2 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 110, 320, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 52 );

    fdui->F3 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 160, 320, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 53 );

    fdui->F4 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 210, 320, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 54 );

    fdui->F5 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 260, 320, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 55 );

    fdui->F6 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 310, 320, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 56 );

    fdui->F7 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 360, 320, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 57 );

    fdui->F8 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 410, 320, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 58 );

    fdui->F9 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 460, 320, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 59 );

    fdui->G2 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 110, 370, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 62 );

    fdui->G3 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 160, 370, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 63 );

    fdui->G4 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 210, 370, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 64 );

    fdui->G5 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 260, 370, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 65 );

    fdui->G6 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 310, 370, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 66 );

    fdui->G7 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 360, 370, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 67 );

    fdui->G8 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 410, 370, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 68 );

    fdui->G9 = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 460, 370, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 69 );

    fdui->BA = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 510, 120, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 20 );

    fdui->CA = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 510, 170, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 30 );

    fdui->DA = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 510, 220, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 40 );

    fdui->EA = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 510, 270, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 50 );

    fdui->FA = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 510, 320, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 60 );

    fdui->GA = obj = fl_add_pixmapbutton( FL_NORMAL_BUTTON, 510, 370, 50, 50, "" );
    fl_set_object_boxtype( obj, FL_FLAT_BOX );
    fl_set_object_color( obj, FL_BLACK, FL_YELLOW );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MB_cb, 70 );

    fl_end_group( );

    fdui->Col1 = obj = fl_add_text( FL_NORMAL_TEXT, 60, 50, 50, 20, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->Col2 = obj = fl_add_text( FL_NORMAL_TEXT, 110, 50, 50, 20, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->Col3 = obj = fl_add_text( FL_NORMAL_TEXT, 160, 50, 50, 20, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->Col4 = obj = fl_add_text( FL_NORMAL_TEXT, 210, 50, 50, 20, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->Col5 = obj = fl_add_text( FL_NORMAL_TEXT, 260, 50, 50, 20, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->Col6 = obj = fl_add_text( FL_NORMAL_TEXT, 310, 50, 50, 20, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->Col7 = obj = fl_add_text( FL_NORMAL_TEXT, 360, 50, 50, 20, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->Col8 = obj = fl_add_text( FL_NORMAL_TEXT, 410, 50, 50, 20, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->Col9 = obj = fl_add_text( FL_NORMAL_TEXT, 460, 50, 50, 20, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->ColA = obj = fl_add_text( FL_NORMAL_TEXT, 510, 50, 50, 20, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->Row1 = obj = fl_add_text( FL_NORMAL_TEXT, 10, 70, 50, 50, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->Row2 = obj = fl_add_text( FL_NORMAL_TEXT, 10, 120, 50, 50, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->Row3 = obj = fl_add_text( FL_NORMAL_TEXT, 10, 170, 50, 50, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->Row4 = obj = fl_add_text( FL_NORMAL_TEXT, 10, 220, 50, 50, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->Row5 = obj = fl_add_text( FL_NORMAL_TEXT, 10, 270, 50, 50, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->Row6 = obj = fl_add_text( FL_NORMAL_TEXT, 10, 320, 50, 50, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->Row7 = obj = fl_add_text( FL_NORMAL_TEXT, 10, 370, 50, 50, "1234" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_resize( obj, FL_RESIZE_NONE );

    fdui->JmRow = obj = fl_add_input( FL_INT_INPUT, 590, 240, 40, 20, "Row" );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT_TOP );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, dummy_cb, 0 );

    fdui->JmCol = obj = fl_add_input( FL_INT_INPUT, 700, 240, 40, 20, "Col" );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT_TOP );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, dummy_cb, 0 );

    fdui->JmpBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 590, 270, 150, 30, "Jump!" );
    fl_set_button_shortcut( obj, "#J", 1 );
    fl_set_object_color( obj, FL_INDIANRED, FL_DARKTOMATO );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_callback( obj, JmpBtn_cb, 0 );

    fdui->HomeBtn = obj = fl_add_button( FL_TOUCH_BUTTON, 650, 120, 30, 30, "@circle" );
    fl_set_button_shortcut( obj, "Hh", 1 );
    fl_set_object_boxtype( obj, FL_RFLAT_BOX );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, DirBtn_cb, 5 );
    fl_set_object_return( obj, FL_RETURN_CHANGED );

    fdui->MapOkButn = obj = fl_add_button( FL_NORMAL_BUTTON, 320, 430, 50, 30, "OK" );
    fl_set_button_shortcut( obj, "#O", 1 );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, MapOk_cb, 0 );

    fl_end_form( );

    fdui->MapForm->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_TasksForm *
create_form_TasksForm( void )
{
    FL_OBJECT *obj;
    FD_TasksForm *fdui = ( FD_TasksForm * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->TasksForm = fl_bgn_form( FL_NO_BOX, 350, 230 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 350, 230, "" );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 350, 40, "" );

    fdui->TasksHelpMenu = obj = fl_add_menu( FL_PULLDOWN_MENU, 300, 10, 40, 20, "Help" );
    fl_set_object_shortcut( obj, "H", 1 );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_callback( obj, TasksHelpMenu_cb, 0 );

    fdui->TasksTasksMenu = obj = fl_add_menu( FL_PULLDOWN_MENU, 10, 10, 40, 20, "Tasks" );
    fl_set_object_shortcut( obj, "T", 1 );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_callback( obj, TasksTasksMenu_cb, 0 );

    fdui->TasksBrowser = obj = fl_add_browser( FL_SELECT_BROWSER, 10, 70, 330, 110, "" );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 50, 40, 20, "Num" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );

    obj = fl_add_text( FL_NORMAL_TEXT, 50, 50, 200, 20, "Description" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );

    obj = fl_add_text( FL_NORMAL_TEXT, 250, 50, 60, 20, "State" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );

    fdui->TasksBtns = fl_bgn_group( );

    fdui->TasksUpdtBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 40, 200, 60, 20, "Update" );
    fl_set_button_shortcut( obj, "#U", 1 );
    fl_set_object_callback( obj, TasksUpdtBtn_cb, 0 );

    fdui->TasksKillBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 230, 200, 60, 20, "Kill" );
    fl_set_button_shortcut( obj, "#K", 1 );
    fl_set_object_callback( obj, TasksKillBtn_cb, 0 );

    fdui->TasksDoneBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 135, 200, 60, 20, "Ok" );
    fl_set_button_shortcut( obj, "#O", 1 );
    fl_set_object_callback( obj, TasksDoneBtn_cb, 0 );

    fl_end_group( );

    fl_end_form( );

    fdui->TasksForm->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_ServCfgForm *
create_form_ServCfgForm( void )
{
    FL_OBJECT *obj;
    FD_ServCfgForm *fdui = ( FD_ServCfgForm * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->ServCfgForm = fl_bgn_form( FL_NO_BOX, 650, 400 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 650, 400, "" );
    fl_set_object_color( obj, FL_TOP_BCOL, FL_COL1 );

    obj = fl_add_box( FL_UP_BOX, 170, 180, 300, 160, "" );

    obj = fl_add_box( FL_UP_BOX, 330, 20, 300, 150, "" );

    obj = fl_add_box( FL_UP_BOX, 20, 20, 300, 150, "" );

    fdui->ServName = obj = fl_add_input( FL_NORMAL_INPUT, 130, 70, 150, 30, "Server Name" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, ServName_cb, 0 );

    fdui->ServPort = obj = fl_add_input( FL_INT_INPUT, 130, 120, 60, 30, "Port" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_callback( obj, ServPort_cb, 0 );

    fdui->PlayerName = obj = fl_add_input( FL_NORMAL_INPUT, 390, 80, 210, 30, "Name" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_callback( obj, PlayerName_cb, 0 );

    fdui->PlayerPswd = obj = fl_add_input( FL_SECRET_INPUT, 390, 120, 150, 30, "Pswd" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, PlayerPswd_cb, 0 );

    fdui->GameDesc = obj = fl_add_input( FL_NORMAL_INPUT, 190, 270, 270, 30, "Game Description" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_TOP );
    fl_set_object_callback( obj, GameDesc_cb, 0 );

    fdui->ServerDataGroup = fl_bgn_group( );

    obj = fl_add_text( FL_NORMAL_TEXT, 30, 30, 280, 30, "Server Data" );
    fl_set_object_lcolor( obj, FL_SLATEBLUE );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_NORMAL_STYLE + FL_EMBOSSED_STYLE );

    fl_end_group( );

    obj = fl_add_text( FL_NORMAL_TEXT, 340, 30, 280, 30, "Player Data" );
    fl_set_object_lcolor( obj, FL_SLATEBLUE );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_NORMAL_STYLE + FL_EMBOSSED_STYLE );

    fdui->ServCfgOkBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 20, 360, 60, 30, "OK" );
    fl_set_button_shortcut( obj, "#O", 1 );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_callback( obj, ServCfgOkBtn_cb, 0 );

    fdui->ServCfgCancelBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 570, 360, 60, 30, "Cancel" );
    fl_set_button_shortcut( obj, "#C", 1 );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_callback( obj, ServCfgCancelBtn_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 180, 190, 280, 30, "World Data" );
    fl_set_object_lcolor( obj, FL_SLATEBLUE );
    fl_set_object_lsize( obj, FL_LARGE_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_NORMAL_STYLE + FL_EMBOSSED_STYLE );

    fl_end_form( );

    fdui->ServCfgForm->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_ShipCensusForm *
create_form_ShipCensusForm( void )
{
    FL_OBJECT *obj;
    FD_ShipCensusForm *fdui = ( FD_ShipCensusForm * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->ShipCensusForm = fl_bgn_form( FL_NO_BOX, 556, 260 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 556, 260, "" );

    fdui->ShBrowse = obj = fl_add_browser( FL_SELECT_BROWSER, 10, 30, 540, 180, "" );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, ShBrowse_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 10, 70, 20, "Number" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 240, 10, 40, 20, "Class" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 280, 10, 70, 20, "Location" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 350, 10, 30, 20, "Crew" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 380, 10, 30, 20, "Effic" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 80, 10, 80, 20, "Name" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    fdui->Update = obj = fl_add_button( FL_NORMAL_BUTTON, 500, 220, 50, 30, "Update" );
    fl_set_button_shortcut( obj, "#U", 1 );
    fl_set_object_callback( obj, ShCenUpdate_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 410, 10, 140, 20, "Last Seen" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 160, 10, 80, 20, "Owner" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    fdui->ShCenOkButn = obj = fl_add_button( FL_NORMAL_BUTTON, 10, 220, 50, 30, "OK" );
    fl_set_button_shortcut( obj, "#O", 1 );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, ShCenOk_cb, 0 );

    fl_end_form( );

    fdui->ShipCensusForm->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_PlanetCensusForm *
create_form_PlanetCensusForm( void )
{
    FL_OBJECT *obj;
    FD_PlanetCensusForm *fdui = ( FD_PlanetCensusForm * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->PlanetCensusForm = fl_bgn_form( FL_NO_BOX, 720, 260 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 720, 260, "" );

    fdui->PlBrowse = obj = fl_add_browser( FL_SELECT_BROWSER, 10, 30, 700, 180, "" );
    fl_set_object_callback( obj, PlBrowse_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 10, 70, 20, "Number" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 160, 10, 80, 20, "Owner" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 240, 10, 40, 20, "Class" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 280, 10, 70, 20, "Location" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 350, 10, 40, 20, "Popu" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 390, 10, 30, 20, "Effic" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 570, 10, 140, 20, "Last Seen" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 80, 10, 80, 20, "Name" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 450, 10, 30, 20, "Wat" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 480, 10, 30, 20, "Ore" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 510, 10, 30, 20, "Gold" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 540, 10, 30, 20, "Polut" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    fdui->Update = obj = fl_add_button( FL_NORMAL_BUTTON, 660, 220, 50, 30, "Update" );
    fl_set_button_shortcut( obj, "Uu", 1 );
    fl_set_object_callback( obj, PlCenUpdate_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 420, 10, 30, 20, "Air" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    fdui->PlCenOkButn = obj = fl_add_button( FL_NORMAL_BUTTON, 10, 220, 50, 30, "OK" );
    fl_set_button_shortcut( obj, "#O", 1 );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, PlCenOk_cb, 0 );

    fl_end_form( );

    fdui->PlanetCensusForm->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_ShipDetailForm *
create_form_ShipDetailForm( void )
{
    FL_OBJECT *obj;
    FD_ShipDetailForm *fdui = ( FD_ShipDetailForm * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->ShipDetailForm = fl_bgn_form( FL_NO_BOX, 500, 440 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 500, 440, "" );

    obj = fl_add_box( FL_FRAME_BOX, 250, 140, 230, 110, "" );
    fl_set_object_color( obj, FL_WHEAT, FL_COL1 );

    obj = fl_add_box( FL_FRAME_BOX, 10, 270, 360, 160, "" );
    fl_set_object_color( obj, FL_WHEAT, FL_COL1 );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 10, 140, 30, "Detailed info for ship:" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    fdui->ShNum = obj = fl_add_text( FL_NORMAL_TEXT, 150, 10, 60, 30, "########" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 40, 470, 10, "@line" );

    obj = fl_add_box( FL_FRAME_BOX, 10, 50, 230, 200, "" );
    fl_set_object_color( obj, FL_WHEAT, FL_COL1 );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 60, 210, 20, "Status" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 30, 80, 40, 20, "Fuel:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 30, 120, 40, 20, "Armor:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Fuel = obj = fl_add_text( FL_NORMAL_TEXT, 70, 80, 50, 20, "######" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->Armor = obj = fl_add_text( FL_NORMAL_TEXT, 70, 120, 50, 20, "#####" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 140, 50, 20, "Shields:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 30, 160, 40, 20, "(keep):" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 30, 180, 40, 20, "Air:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 100, 50, 20, "Energy:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Energy = obj = fl_add_text( FL_NORMAL_TEXT, 70, 100, 50, 20, "#####" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 150, 80, 40, 20, "Effic:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Effic = obj = fl_add_text( FL_NORMAL_TEXT, 190, 80, 40, 20, "100" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->Shields = obj = fl_add_text( FL_NORMAL_TEXT, 70, 140, 50, 20, "#####" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->ShKeep = obj = fl_add_text( FL_NORMAL_TEXT, 70, 160, 50, 20, "#####" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->Air = obj = fl_add_text( FL_NORMAL_TEXT, 70, 180, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 220, 10, 60, 30, "Owner:" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    fdui->Owner = obj = fl_add_text( FL_NORMAL_TEXT, 280, 10, 80, 30, "Owner" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 370, 10, 30, 30, "At:" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    fdui->RowCol = obj = fl_add_text( FL_NORMAL_TEXT, 400, 10, 90, 30, "ROW, COL" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 150, 100, 40, 20, "TF:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->TF = obj = fl_add_text( FL_NORMAL_TEXT, 190, 100, 40, 20, "TF" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 140, 140, 50, 20, "Eng TF:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Plague = obj = fl_add_text( FL_NORMAL_TEXT, 190, 180, 40, 20, "Yes" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 140, 120, 50, 20, "Hull TF:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 150, 180, 40, 20, "Plague:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 140, 160, 50, 20, "Eng Eff:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->HullTF = obj = fl_add_text( FL_NORMAL_TEXT, 190, 120, 40, 20, "TF" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->EngTF = obj = fl_add_text( FL_NORMAL_TEXT, 190, 140, 40, 20, "TF" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->EngEff = obj = fl_add_text( FL_NORMAL_TEXT, 190, 160, 40, 20, "100" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_box( FL_FRAME_BOX, 250, 50, 230, 80, "" );
    fl_set_object_color( obj, FL_WHEAT, FL_COL1 );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 60, 210, 20, "Passengers" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 80, 40, 20, "Civ:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Civ = obj = fl_add_text( FL_NORMAL_TEXT, 300, 80, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 100, 40, 20, "Mil:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Mil = obj = fl_add_text( FL_NORMAL_TEXT, 300, 100, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->Sci = obj = fl_add_text( FL_NORMAL_TEXT, 430, 80, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 390, 80, 40, 20, "Sci:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Ofc = obj = fl_add_text( FL_NORMAL_TEXT, 430, 100, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 390, 100, 40, 20, "Ofc:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 280, 240, 20, "Big Items" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->ShDetItem = obj = fl_add_browser( FL_HOLD_BROWSER, 20, 320, 260, 100, "" );
    fl_set_object_color( obj, FL_COL1, FL_YELLOW );
    fl_set_object_callback( obj, dummy_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 170, 40, 20, "Torp:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 150, 210, 20, "Small Cargo" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 190, 40, 20, "Ore:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 210, 40, 20, "Bars:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Torp = obj = fl_add_text( FL_NORMAL_TEXT, 300, 170, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->Ore = obj = fl_add_text( FL_NORMAL_TEXT, 300, 190, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->Bars = obj = fl_add_text( FL_NORMAL_TEXT, 300, 210, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 380, 170, 50, 20, "Air Tnk:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->AirTnk = obj = fl_add_text( FL_NORMAL_TEXT, 430, 170, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 380, 190, 50, 20, "Fuel  Tnk:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 370, 210, 60, 20, "Available:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->FuelTnk = obj = fl_add_text( FL_NORMAL_TEXT, 430, 190, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->Cargo = obj = fl_add_text( FL_NORMAL_TEXT, 430, 210, 40, 20, "######" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 200, 60, 20, "Last Seen:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Seen = obj = fl_add_text( FL_NORMAL_TEXT, 80, 200, 150, 20, "Needs to be able to hold 26" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );

    fdui->ShDetUpdBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 380, 270, 50, 30, "Update" );
    fl_set_button_shortcut( obj, "#U", 1 );
    fl_set_object_callback( obj, ShDetUpdBtn_cb, 0 );

    fdui->ShDetStatBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 380, 310, 50, 30, "Status" );
    fl_set_button_shortcut( obj, "#S", 1 );
    fl_set_object_callback( obj, ShDetStatBtn_cb, 0 );

    fdui->ShDetCargoBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 380, 350, 50, 30, "Cargo" );
    fl_set_button_shortcut( obj, "#C", 1 );
    fl_set_object_callback( obj, ShDetCargoBtn_cb, 0 );

    fdui->ShDetBigBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 380, 390, 50, 30, "Big" );
    fl_set_button_shortcut( obj, "#B", 1 );
    fl_set_object_callback( obj, ShDetBigBtn_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 300, 70, 20, "Number" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 90, 300, 30, 20, "Type" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 120, 300, 30, 20, "TF" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 150, 300, 30, 20, "Eff" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 230, 300, 30, 20, "Inst" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    fdui->ShDetInstallBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 300, 320, 50, 20, "Install" );
    fl_set_object_callback( obj, ShDetActionBtn_cb, 1 );

    fdui->ShDetUninstallBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 300, 340, 50, 20, "Uninstall" );
    fl_set_object_callback( obj, ShDetActionBtn_cb, 2 );

    fdui->ShDetUnloadBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 300, 360, 50, 20, "Unload" );
    fl_set_object_callback( obj, ShDetActionBtn_cb, 3 );

    obj = fl_add_text( FL_NORMAL_TEXT, 180, 300, 50, 20, "Weight" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    fdui->Where = obj = fl_add_text( FL_NORMAL_TEXT, 30, 220, 170, 20, "Needs to be able to hold 26" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    fdui->ShDetOkButn = obj = fl_add_button( FL_NORMAL_BUTTON, 440, 390, 50, 30, "OK" );
    fl_set_button_shortcut( obj, "#O", 1 );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, ShDetOk_cb, 0 );

    fl_end_form( );

    fdui->ShipDetailForm->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_PlanetDetailForm *
create_form_PlanetDetailForm( void )
{
    FL_OBJECT *obj;
    FD_PlanetDetailForm *fdui = ( FD_PlanetDetailForm * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->PlanetDetailForm = fl_bgn_form( FL_NO_BOX, 730, 500 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 730, 500, "" );

    obj = fl_add_box( FL_FRAME_BOX, 490, 70, 230, 160, "" );
    fl_set_object_color( obj, FL_WHEAT, FL_COL1 );

    obj = fl_add_text( FL_NORMAL_TEXT, 500, 80, 150, 20, "Production" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->Name = obj = fl_add_input( FL_NORMAL_INPUT, 50, 30, 130, 30, "Name:" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, dummy_cb, 0 );

    obj = fl_add_box( FL_FRAME_BOX, 10, 70, 230, 220, "" );
    fl_set_object_color( obj, FL_WHEAT, FL_COL1 );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 10, 160, 20, "Detailed info for planet:" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->PlNum = obj = fl_add_text( FL_NORMAL_TEXT, 170, 10, 70, 20, "########" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 240, 10, 60, 20, "Owner:" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Owner = obj = fl_add_text( FL_NORMAL_TEXT, 300, 10, 80, 20, "Owner" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 380, 10, 30, 20, "At:" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    fdui->RowCol = obj = fl_add_text( FL_NORMAL_TEXT, 410, 10, 90, 20, "ROW, COL" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 60, 710, 10, "@line" );

    fdui->Seen = obj = fl_add_text( FL_NORMAL_TEXT, 80, 260, 150, 20, "Needs to be able to hold 26" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 260, 60, 20, "Last Seen:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 80, 210, 20, "Population" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 100, 40, 20, "Civ:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Civ = obj = fl_add_text( FL_NORMAL_TEXT, 60, 100, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 120, 40, 20, "Mil:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Mil = obj = fl_add_text( FL_NORMAL_TEXT, 60, 120, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->Sci = obj = fl_add_text( FL_NORMAL_TEXT, 190, 100, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 150, 100, 40, 20, "Sci:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Ofc = obj = fl_add_text( FL_NORMAL_TEXT, 190, 120, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 150, 120, 40, 20, "Ofc:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_box( FL_FRAME_BOX, 250, 70, 230, 100, "" );
    fl_set_object_color( obj, FL_WHEAT, FL_COL1 );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 100, 40, 20, "Misl:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 80, 210, 20, "Commodities" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 140, 40, 20, "Ore:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Misl = obj = fl_add_text( FL_NORMAL_TEXT, 300, 100, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->Ore = obj = fl_add_text( FL_NORMAL_TEXT, 300, 140, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 380, 100, 50, 20, "Air Tnk:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->AirTnk = obj = fl_add_text( FL_NORMAL_TEXT, 430, 100, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 380, 120, 50, 20, "Fuel  Tnk:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->FuelTnk = obj = fl_add_text( FL_NORMAL_TEXT, 430, 120, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 120, 40, 20, "Plane:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Plane = obj = fl_add_text( FL_NORMAL_TEXT, 300, 120, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 390, 140, 40, 20, "Bars:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Bars = obj = fl_add_text( FL_NORMAL_TEXT, 430, 140, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->PlProdBrowse = obj = fl_add_browser( FL_NORMAL_BROWSER, 500, 120, 210, 100, "" );
    fl_set_object_color( obj, FL_COL1, FL_YELLOW );
    fl_set_object_callback( obj, dummy_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 500, 100, 100, 20, "Type" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_box( FL_FRAME_BOX, 250, 180, 230, 140, "" );
    fl_set_object_color( obj, FL_WHEAT, FL_COL1 );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 190, 210, 20, "Geographic" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 210, 40, 20, "Size:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Size = obj = fl_add_text( FL_NORMAL_TEXT, 300, 210, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 230, 40, 20, "Effic:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Effic = obj = fl_add_text( FL_NORMAL_TEXT, 300, 230, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->Class = obj = fl_add_text( FL_NORMAL_TEXT, 430, 210, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 390, 210, 40, 20, "Class:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Polut = obj = fl_add_text( FL_NORMAL_TEXT, 430, 230, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 390, 230, 40, 20, "Polut:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 250, 40, 20, "Minrl:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Minerals = obj = fl_add_text( FL_NORMAL_TEXT, 300, 250, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->Gold = obj = fl_add_text( FL_NORMAL_TEXT, 430, 250, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 390, 250, 40, 20, "Gold:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 270, 40, 20, "Water:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Water = obj = fl_add_text( FL_NORMAL_TEXT, 300, 270, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->Gas = obj = fl_add_text( FL_NORMAL_TEXT, 430, 270, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 390, 270, 40, 20, "Gas:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 260, 290, 40, 20, "Mobil:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Mobil = obj = fl_add_text( FL_NORMAL_TEXT, 300, 290, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->Plague = obj = fl_add_text( FL_NORMAL_TEXT, 430, 290, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 390, 290, 40, 20, "Plague:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 140, 40, 20, "TchLv:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Tech = obj = fl_add_text( FL_NORMAL_TEXT, 60, 140, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->Research = obj = fl_add_text( FL_NORMAL_TEXT, 190, 140, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 140, 140, 50, 20, "Res Lv:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 160, 40, 20, "TF:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->TF = obj = fl_add_text( FL_NORMAL_TEXT, 60, 160, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->RF = obj = fl_add_text( FL_NORMAL_TEXT, 190, 160, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 150, 160, 40, 20, "RF:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 200, 60, 20, "Prev Own:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->PrevOwn = obj = fl_add_text( FL_NORMAL_TEXT, 80, 200, 120, 20, "Previous Owner Here" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 220, 60, 20, "Transfer:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->Transfer = obj = fl_add_text( FL_NORMAL_TEXT, 80, 220, 110, 20, "HOSTILE" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 240, 70, 20, "Owner Relat:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->OwnerRel = obj = fl_add_text( FL_NORMAL_TEXT, 90, 240, 100, 20, "*WAR*" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->Checkpoint = obj = fl_add_input( FL_NORMAL_INPUT, 320, 30, 130, 30, "Checkpoint:" );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, dummy_cb, 0 );

    fdui->NameUpdate = obj = fl_add_button( FL_NORMAL_BUTTON, 190, 40, 30, 20, "Upd" );
    fl_set_object_color( obj, FL_INDIANRED, FL_DARKTOMATO );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, NameUpdate_cb, 0 );

    fdui->CheckpointUpdate = obj = fl_add_button( FL_NORMAL_BUTTON, 460, 40, 30, 20, "Upd" );
    fl_set_object_color( obj, FL_INDIANRED, FL_DARKTOMATO );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, CheckpointUpdate_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 600, 100, 50, 20, "Avail" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 650, 100, 40, 20, "Pct" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 650, 80, 30, 20, "BTU:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->BTU = obj = fl_add_text( FL_NORMAL_TEXT, 680, 80, 30, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_box( FL_FRAME_BOX, 10, 330, 320, 160, "" );
    fl_set_object_color( obj, FL_WHEAT, FL_COL1 );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 340, 240, 20, "Big Items" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->PlDetItem = obj = fl_add_browser( FL_HOLD_BROWSER, 20, 380, 230, 100, "" );
    fl_set_object_color( obj, FL_COL1, FL_YELLOW );
    fl_set_object_callback( obj, dummy_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 360, 70, 20, "Number" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 90, 360, 30, 20, "Type" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 120, 360, 30, 20, "TF" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 150, 360, 30, 20, "Eff" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    fdui->PlDetRefurbBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 260, 380, 50, 20, "Refurb" );
    fl_set_object_callback( obj, PlDetActionBtn_cb, 1 );

    obj = fl_add_text( FL_NORMAL_TEXT, 180, 360, 50, 20, "Weight" );
    fl_set_object_boxtype( obj, FL_FRAME_BOX );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );

    obj = fl_add_text( FL_NORMAL_TEXT, 360, 330, 170, 30, "I know this form is ugly," );
    fl_set_object_lcolor( obj, FL_RED );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    obj = fl_add_text( FL_NORMAL_TEXT, 360, 360, 170, 30, "I'm working on it" );
    fl_set_object_lcolor( obj, FL_RED );
    fl_set_object_lsize( obj, FL_MEDIUM_SIZE );

    fdui->PlDetUpdBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 490, 240, 50, 30, "Update" );
    fl_set_button_shortcut( obj, "#U", 1 );
    fl_set_object_callback( obj, PlDetUpdBtn_cb, 0 );

    fdui->PlDetGeoBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 550, 240, 50, 30, "Geo" );
    fl_set_button_shortcut( obj, "#G", 1 );
    fl_set_object_callback( obj, PlDetGeoBtn_cb, 0 );

    fdui->PlDetPopBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 610, 240, 50, 30, "Popu" );
    fl_set_button_shortcut( obj, "#P", 1 );
    fl_set_object_callback( obj, PlDetPopBtn_cb, 0 );

    fdui->PlDetBigBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 670, 240, 50, 30, "Big" );
    fl_set_button_shortcut( obj, "#B", 1 );
    fl_set_object_callback( obj, PlDetBigBtn_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 20, 180, 40, 20, "PF:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->PF = obj = fl_add_text( FL_NORMAL_TEXT, 60, 180, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    fdui->PopPct = obj = fl_add_text( FL_NORMAL_TEXT, 190, 180, 40, 20, "###" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );

    obj = fl_add_text( FL_NORMAL_TEXT, 140, 180, 50, 20, "Pop %:" );
    fl_set_object_color( obj, FL_WHEAT, FL_MCOL );
    fl_set_object_lalign( obj, FL_ALIGN_RIGHT | FL_ALIGN_INSIDE );

    fdui->PlDetProdBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 550, 280, 50, 30, "Prod" );
    fl_set_button_shortcut( obj, "#R", 1 );
    fl_set_object_callback( obj, PlDetProdBtn_cb, 0 );

    fdui->PlDetDumpBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 490, 280, 50, 30, "Dump" );
    fl_set_button_shortcut( obj, "#D", 1 );
    fl_set_object_color( obj, FL_INDIANRED, FL_DARKTOMATO );
    fl_set_object_callback( obj, PlDetDumpBtn_cb, 0 );

    fdui->PlDetOkButn = obj = fl_add_button( FL_NORMAL_BUTTON, 670, 460, 50, 30, "OK" );
    fl_set_button_shortcut( obj, "#O", 1 );
    fl_set_object_resize( obj, FL_RESIZE_NONE );
    fl_set_object_callback( obj, PlDetOk_cb, 0 );

    fl_end_form( );

    fdui->PlanetDetailForm->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_PowerRptForm *
create_form_PowerRptForm( void )
{
    FL_OBJECT *obj;
    FD_PowerRptForm *fdui = ( FD_PowerRptForm * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->PowerRptForm = fl_bgn_form( FL_NO_BOX, 380, 230 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 380, 230, "" );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 10, 360, 40, "Current Power Report" );
    fl_set_object_lcolor( obj, FL_BLUE );
    fl_set_object_lsize( obj, FL_HUGE_SIZE );
    fl_set_object_lalign( obj, FL_ALIGN_CENTER );
    fl_set_object_lstyle( obj, FL_NORMAL_STYLE + FL_EMBOSSED_STYLE );

    fl_end_form( );

    fdui->PowerRptForm->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_MinerCensusForm *
create_form_MinerCensusForm( void )
{
    FL_OBJECT *obj;
    FD_MinerCensusForm *fdui = ( FD_MinerCensusForm * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->MinerCensusForm = fl_bgn_form( FL_NO_BOX, 380, 230 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 380, 230, "" );

    obj = fl_add_browser( FL_NORMAL_BROWSER, 10, 50, 360, 170, "" );
    fl_set_object_color( obj, FL_COL1, FL_YELLOW );

    fl_end_form( );

    fdui->MinerCensusForm->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_DebugOutputForm *
create_form_DebugOutputForm( void )
{
    FL_OBJECT *obj;
    FD_DebugOutputForm *fdui = ( FD_DebugOutputForm * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->DebugOutputForm = fl_bgn_form( FL_NO_BOX, 380, 230 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 380, 230, "" );

    obj = fl_add_browser( FL_NORMAL_BROWSER, 10, 40, 360, 160, "" );
    fl_set_object_color( obj, FL_COL1, FL_YELLOW );

    fl_end_form( );

    fdui->DebugOutputForm->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_LocalEditorForm *
create_form_LocalEditorForm( void )
{
    FL_OBJECT *obj;
    FD_LocalEditorForm *fdui = ( FD_LocalEditorForm * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->LocalEditorForm = fl_bgn_form( FL_NO_BOX, 380, 230 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 380, 230, "" );

    obj = fl_add_text( FL_NORMAL_TEXT, 50, 30, 270, 50, "This will be a form to handle local message composition" );

    fl_end_form( );

    fdui->LocalEditorForm->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_Dummy1Form *
create_form_Dummy1Form( void )
{
    FL_OBJECT *obj;
    FD_Dummy1Form *fdui = ( FD_Dummy1Form * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->Dummy1Form = fl_bgn_form( FL_NO_BOX, 380, 230 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 380, 230, "" );

    fl_end_form( );

    fdui->Dummy1Form->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_Dummy2Form *
create_form_Dummy2Form( void )
{
    FL_OBJECT *obj;
    FD_Dummy2Form *fdui = ( FD_Dummy2Form * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->Dummy2Form = fl_bgn_form( FL_NO_BOX, 380, 230 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 380, 230, "" );

    fl_end_form( );

    fdui->Dummy2Form->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_Dummy3Form *
create_form_Dummy3Form( void )
{
    FL_OBJECT *obj;
    FD_Dummy3Form *fdui = ( FD_Dummy3Form * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->Dummy3Form = fl_bgn_form( FL_NO_BOX, 380, 230 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 380, 230, "" );

    fl_end_form( );

    fdui->Dummy3Form->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_Dummy4Form *
create_form_Dummy4Form( void )
{
    FL_OBJECT *obj;
    FD_Dummy4Form *fdui = ( FD_Dummy4Form * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->Dummy4Form = fl_bgn_form( FL_NO_BOX, 380, 230 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 380, 230, "" );

    fl_end_form( );

    fdui->Dummy4Form->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_Dummy5Form *
create_form_Dummy5Form( void )
{
    FL_OBJECT *obj;
    FD_Dummy5Form *fdui = ( FD_Dummy5Form * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->Dummy5Form = fl_bgn_form( FL_NO_BOX, 380, 230 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 380, 230, "" );

    fl_end_form( );

    fdui->Dummy5Form->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_HelpForm *
create_form_HelpForm( void )
{
    FL_OBJECT *obj;
    FD_HelpForm *fdui = ( FD_HelpForm * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->HelpForm = fl_bgn_form( FL_NO_BOX, 570, 390 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 570, 390, "" );

    fdui->Help_Browser = obj = fl_add_browser( FL_NORMAL_BROWSER, 10, 10, 550, 330, "" );
    fl_set_object_color( obj, FL_COL1, FL_YELLOW );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_callback( obj, dummy_cb, 0 );

    fdui->OkBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 240, 350, 50, 30, "Ok!" );
    fl_set_button_shortcut( obj, "Oo", 1 );
    fl_set_object_callback( obj, HelpOk_cb, 0 );

    fl_end_form( );

    fdui->HelpForm->fdui = fdui;

    return fdui;
}

/***************************************
 ***************************************/

FD_CommandForm *
create_form_CommandForm( void )
{
    FL_OBJECT *obj;
    FD_CommandForm *fdui = ( FD_CommandForm * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->CommandForm = fl_bgn_form( FL_NO_BOX, 370, 330 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 370, 330, "" );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 370, 40, "" );

    fdui->CmdsHelpMenu = obj = fl_add_menu( FL_PULLDOWN_MENU, 320, 10, 40, 20, "Help" );
    fl_set_object_shortcut( obj, "#H", 1 );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );
    fl_set_object_lstyle( obj, FL_BOLD_STYLE );
    fl_set_object_callback( obj, CmdsHelpMenu_cb, 0 );

    fdui->CmdsBrowser = obj = fl_add_browser( FL_HOLD_BROWSER, 10, 70, 350, 130, "" );
    fl_set_object_color( obj, FL_COL1, FL_YELLOW );
    fl_set_object_callback( obj, CmdsBrowser_cb, 0 );

    obj = fl_add_text( FL_NORMAL_TEXT, 10, 50, 40, 20, "Num" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );

    obj = fl_add_text( FL_NORMAL_TEXT, 50, 50, 220, 20, "Description" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );

    obj = fl_add_text( FL_NORMAL_TEXT, 270, 50, 60, 20, "Priority" );
    fl_set_object_boxtype( obj, FL_BORDER_BOX );
    fl_set_object_lsize( obj, FL_NORMAL_SIZE );

    fdui->CmdsKillBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 10, 10, 60, 20, "Kill" );
    fl_set_button_shortcut( obj, "#K", 1 );
    fl_set_object_color( obj, FL_INDIANRED, FL_DARKTOMATO );
    fl_set_object_callback( obj, CmdsKillBtn_cb, 0 );

    fdui->CmdsDoneBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 10, 290, 60, 30, "Ok" );
    fl_set_button_shortcut( obj, "#O", 1 );
    fl_set_object_callback( obj, CmdsDoneBtn_cb, 0 );

    fdui->CmdsPauseBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 300, 290, 60, 30, "Pause" );
    fl_set_button_shortcut( obj, "#P", 1 );
    fl_set_object_callback( obj, CmdsPauseBtn_cb, 0 );

    fdui->CmdsAddBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 150, 250, 60, 20, "Add" );
    fl_set_button_shortcut( obj, "#A", 1 );
    fl_set_object_callback( obj, CmdsAddBtn_cb, 0 );

    fdui->CmdsCmd = obj = fl_add_input( FL_NORMAL_INPUT, 60, 210, 300, 30, "Command" );
    fl_set_object_callback( obj, dummy_cb, 0 );

    fdui->CmdsPriorBtn = obj = fl_add_choice( FL_NORMAL_CHOICE2, 60, 250, 80, 30, "Priority" );
    fl_set_object_callback( obj, dummy_cb, 0 );

    fdui->CmdsModBtn = obj = fl_add_button( FL_NORMAL_BUTTON, 220, 250, 60, 20, "Modify" );
    fl_set_button_shortcut( obj, "#M", 1 );
    fl_set_object_callback( obj, CmdsModBtn_cb, 0 );

    fl_end_form( );

    fdui->CommandForm->fdui = fdui;

    return fdui;
}
